In [188]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [186]:
n_simulations = 100_000

### How likely is it that you roll doubles when rolling two dice?

In [187]:
outcomes = [1,2,3,4,5,6]
n_dice = 2

In [192]:
rolls = np.random.choice(outcomes, size=(n_simulations, n_dice))
rolls

array([[3, 5],
       [5, 6],
       [6, 1],
       ...,
       [3, 3],
       [5, 4],
       [1, 1]])

In [194]:
rolls =pd.DataFrame(rolls)
rolls

0  1
0      3  5
1      5  6
2      6  1
3      2  3
4      2  4
...   .. ..
99995  4  2
99996  5  3
99997  3  3
99998  5  4
99999  1  1

[100000 rows x 2 columns]

In [199]:
(rolls[0] == rolls[1]).mean()

0.16737

In [11]:
# answer: ~0.16

### If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [200]:
outcomes = ['H','T']
n_coins = 8

In [202]:
coinflips = np.random.choice(outcomes, size=(n_simulations, n_coins))
coinflips

array([['H', 'T', 'T', ..., 'H', 'H', 'H'],
       ['H', 'H', 'H', ..., 'T', 'T', 'H'],
       ['H', 'T', 'T', ..., 'H', 'H', 'T'],
       ...,
       ['H', 'T', 'T', ..., 'H', 'H', 'T'],
       ['T', 'T', 'H', ..., 'T', 'T', 'H'],
       ['T', 'T', 'H', ..., 'H', 'T', 'H']], dtype='<U1')

In [207]:
flips_by_sim = (coinflips == 'H').sum(axis=1)
flips_by_sim

array([4, 5, 5, ..., 4, 3, 4])

In [210]:
(flips_by_sim == 3).mean()

0.21676

In [211]:
# answer: ~0.22

### What is the probability of getting more than 3 heads?

In [212]:
outcomes = ['H','T']
n_coins = 8

coinflips = np.random.choice(outcomes, size=(n_simulations, n_coins))
flips_by_sim = (coinflips == 'H').sum(axis=1)
(flips_by_sim > 3).mean()

0.63702

In [213]:
# answer: ~0.64

### There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [214]:
outcomes = ['wd', 'wd', 'wd', 'ds']
n_billboards = 2

# billboards = np.random.choice(outcomes, size=(n_simulations, n_billboards))
# billboards

In [227]:
outcomes = ['wd','ds']

billboards = np.random.choice(outcomes, size=(n_simulations, n_billboards), 
                p=[0.75, 0.25] )
billboards

array([['ds', 'ds'],
       ['wd', 'wd'],
       ['wd', 'wd'],
       ...,
       ['wd', 'wd'],
       ['wd', 'wd'],
       ['wd', 'wd']], dtype='<U2')

In [228]:
(billboards == 'ds').sum(axis=1)

array([2, 0, 0, ..., 0, 0, 0])

In [229]:
((billboards == 'ds').sum(axis=1) == 2).mean()

0.0623

In [230]:
# answer ~0.06

### Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [231]:
mean = 3 
sd = 1.5

n_days = 5

In [236]:
poptarts_bought_day = np.random.normal(mean, sd, size=(n_simulations, n_days))
poptarts_bought_day

array([[ 5.28644864,  2.34286252,  3.88858775,  2.89355051,  3.73476916],
       [ 3.25851922,  4.98912721,  3.10623076,  3.26543655,  1.47142155],
       [ 6.25478857,  0.94324798,  1.9270972 ,  3.37648979,  2.04785375],
       ...,
       [ 1.98507894,  3.11740855,  1.53918779,  5.10255448, -0.51770085],
       [ 2.7153372 ,  1.39518863,  2.13539662,  1.77375428,  2.75231773],
       [ 0.42870835,  3.26742687,  3.33232612,  4.39224438,  3.0542598 ]])

In [238]:
poptarts_bought_per_week = poptarts_bought_day.sum(axis=1)
poptarts_bought_per_week

array([18.14621858, 16.09073529, 14.54947728, ..., 11.2265289 ,
       10.77199447, 14.47496552])

In [252]:
(poptarts_bought_per_week < 0).sum()

1

In [253]:
(poptarts_bought_per_week < 17).mean()

0.72411

In [254]:
# answer: ~0.72 or ~0.62 ?????

### Compare Heights
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [258]:
men_mean = 178
men_sd = 8

women_mean = 170
women_sd = 6

In [262]:
men_height =  np.random.normal(men_mean, men_sd, n_simulations)
men_height

array([173.37683976, 180.76473978, 179.96409798, ..., 173.14241134,
       181.12998372, 172.23351088])

In [264]:
women_height = np.random.normal(women_mean, women_sd, n_simulations)
women_height

array([167.86744029, 169.23649381, 176.92246148, ..., 166.43261188,
       171.84001332, 168.58669101])

In [266]:
(women_height > men_height).mean()

0.21235

In [267]:
# answer ~0.21

### When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [268]:
outcomes = ['S', 'F']
n_students = 50

In [272]:
downloads = np.random.choice(outcomes, size=(n_simulations, n_students), 
                p = [249/250, 1/250])
downloads

array([['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ...,
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S']], dtype='<U1')

In [274]:
(downloads == 'S').sum(axis=1)

array([50, 50, 50, ..., 49, 50, 50])

In [277]:
((downloads == 'S').sum(axis=1) == 50).mean()

0.8179

In [123]:
# answer: ~0.82

### 100 students?

In [281]:
outcomes = ['S', 'F']
n_students = 100

downloads = np.random.choice(outcomes, size=(n_simulations, n_students), 
                p = [249/250, 1/250])

((downloads == 'S').sum(axis=1) == n_students).mean()

0.67063

In [282]:
# answer: ~0.67

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [283]:
outcomes = ['S', 'F']
n_students = 150

downloads = np.random.choice(outcomes, size=(n_simulations, n_students), 
                p = [249/250, 1/250])

((downloads == 'S').sum(axis=1) < n_students).mean()

0.45189

In [284]:
# answer: ~0.45

### How likely is it that 450 students all download anaconda without an issue?

In [285]:
outcomes = ['S', 'F']
n_students = 450

downloads = np.random.choice(outcomes, size=(n_simulations, n_students), 
                p = [249/250, 1/250])

((downloads == 'S').sum(axis=1) == n_students).mean()

0.1645

In [286]:
# answer: ~0.16

### There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [290]:
p_food_truck = 0.70
n_days = 3

In [295]:
is_food_truck = np.random.random((n_simulations,n_days))
is_food_truck

array([[0.40237801, 0.59427314, 0.30093324],
       [0.24774932, 0.12535787, 0.5458306 ],
       [0.98137218, 0.66744466, 0.42889375],
       ...,
       [0.27378455, 0.19047117, 0.34804088],
       [0.87253118, 0.79983227, 0.16578583],
       [0.50885268, 0.36567926, 0.14260405]])

In [297]:
yes_food_truck = (is_food_truck < p_food_truck)
yes_food_truck

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       ...,
       [ True,  True,  True],
       [False, False,  True],
       [ True,  True,  True]])

In [303]:
(yes_food_truck.sum(axis=1) == 0).mean()

0.02808

In [304]:
# answer: ~0.02

### How likely is it that a food truck will show up sometime this week?

In [306]:
p_food_truck = 0.70
n_days = 7

is_food_truck = np.random.random((n_simulations,n_days))
yes_food_truck = (is_food_truck < p_food_truck)

(yes_food_truck.sum(axis=1) > 0).mean()

0.99985

In [307]:
# answer: ~0.99

### If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [310]:
outcome = range(366)
n_people = 23

In [313]:
birthdays = np.random.choice(outcome, size=(n_simulations, n_people))
birthdays

array([[ 13, 124,  66, ...,  60, 335, 197],
       [187, 289, 221, ..., 334, 158,  48],
       [202, 299,   5, ..., 280, 145, 326],
       ...,
       [ 75, 218, 156, ..., 360,  69, 261],
       [196, 158, 166, ..., 339, 354, 149],
       [264, 120, 119, ..., 256, 353, 134]])

In [315]:
birthdays = pd.DataFrame(birthdays)
birthdays

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0       13  124   66  214  263  150  102  100  248  245  ...  138  230  352   
1      187  289  221  311  293  359   12  284  214  327  ...  165  168  364   
2      202  299    5  123  314  207  310   41  359  303  ...  314   88  141   
3      238  295  326   45  209   82  204  359  116  289  ...  239   23   70   
4       34  170  241   17  109   87   50  161  289  292  ...  162  310  220   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  265  185    1  317  290   65   14  308  350  180  ...   32  108   82   
99996  212   59   26  355  158   62  217  198  285    1  ...  363  297  237   
99997   75  218  156  345  283  204   19  262   21   83  ...  184  103  262   
99998  196  158  166   69  295  163  232  175  244  337  ...  127   38   46   
99999  264  120  119   50  365  141  180   82  240  327  ...   41  318  143   

        16   17   18   19   20   21   22  
0       71    3  165   61   60  335  197  
1      171  298  352  232  334  158   48  
2      356   68  133   43  280  145  326  
3      145  189  177  156  323  152   99  
4      145  236  127  353  228  362  341  
...    ...  ...  ...  ...  ...  ...  ...  
99995  354  194  308  184  281   82  329  
99996  315  260  162   62  229  255  182  
99997   23  327  303  196  360   69  261  
99998  197  349   30  306  339  354  149  
99999  286   64  212  121  256  353  134  

[100000 rows x 23 columns]

In [327]:
(birthdays.nunique(axis=1) < 23).mean()

0.50699

In [ ]:
# answer: ~0.50

### What if it's 20 people? 

In [328]:
outcome = range(366)
n_people = 20

birthdays = np.random.choice(outcome, size=(n_simulations, n_people))
birthdays = pd.DataFrame(birthdays)

(birthdays.nunique(axis=1) < n_people).mean()

0.41011

In [182]:
# answer: ~0.41

### 40?

In [329]:
outcome = range(366)
n_people = 40

birthdays = np.random.choice(outcome, size=(n_simulations, n_people))
birthdays = pd.DataFrame(birthdays)

(birthdays.nunique(axis=1) < n_people).mean()

0.89026

In [ ]:
# answer: ~0.89